create table Ingredient (
  id varchar(4) not null,
  name varchar(25) not null,
  type varchar(10) not null,
  primary key (id)
);

create table Taco (
  id bigint generated by default as identity,
  createdat timestamp not null,
  name varchar(50) not null,
  tacoorder bigint,
  primary key (id)
);

create table Taco_Ingredients (
  taco bigint not null,
  ingredient varchar(4) not null,
  primary key (taco, ingredient)
);

alter table Taco_Ingredients
    add constraint FK6nu5u5fox7xjxt3npeh7wxnp
        foreign key (taco)
            references Taco;

alter table Taco_Ingredients
    add constraint FKs3qlpxo36n3b33fl2yyl5f0fr
        foreign key (ingredient)
            references Ingredient;

create table Taco_Order (
  id bigint generated by default as identity,
  cccvv varchar(3) not null,
  ccexpiration varchar(5) not null,
  ccnumber varchar(16) not null,
  deliverycity varchar(50) not null,
  deliveryname varchar(50) not null,
  deliverystate varchar(2) not null,
  deliverystreet varchar(50) not null,
  deliveryzip varchar(10) not null,
  placedat timestamp not null,
  primary key (id)
);

alter table Taco
  add constraint FKj4l1msfxkjjdsr8p61i0v7v3y
    foreign key (tacoorder)
      references Taco_Order;
